# Generated by Django 3.0.2 on 2020-04-29 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('book', models.FileField(upload_to='docs/')),
                ('book_genre', models.CharField(choices=[('Fantasy', 'Fantasy'), ('Adventure', 'Adventure'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Science Fiction', 'Science Fiction')], max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
